import 'farm_heatmap_screen.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'results_screen.dart';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  bool _isLoading = false;
  final ImagePicker _picker = ImagePicker();

  // ⚠️ IMPORTANT: Replace this with the URL generated by your Colab cell!
  // It should look something like: 'https://xxxx-xxx.ngrok-free.app/api/v1/diagnose'
  final String apiUrl = 'YOUR_COLAB_URL_HERE/api/v1/diagnose'; 

  Future<void> _scanLeaf() async {
    try {
      // 1. Open the camera to take a photo
      final XFile? image = await _picker.pickImage(source: ImageSource.camera);
      
      if (image == null) return; // User canceled the camera

      // 2. Start the loading animation
      setState(() {
        _isLoading = true;
      });

      // 3. Prepare the Multipart HTTP Request
      var request = http.MultipartRequest('POST', Uri.parse(apiUrl));
      
      // Add the required form fields we defined in FastAPI
      request.fields['farm_location'] = 'Rutsiro';
      request.fields['hardware_id'] = 'App-MVP-01';
      
      // Attach the image file
      request.files.add(await http.MultipartFile.fromPath('file', image.path));

      // 4. Send the request to the AI model
      var response = await request.send();
      var responseData = await response.stream.bytesToString();
      var jsonResponse = json.decode(responseData);

      // 5. Stop loading
      setState(() {
        _isLoading = false;
      });

      // 6. Check if successful and navigate to Results Screen
      if (response.statusCode == 200 && jsonResponse['status'] == 'success') {
        var results = jsonResponse['inference_results'];
        
        if (!mounted) return;
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => ResultsScreen(
              diseaseClass: results['disease_class'],
              confidenceScore: results['confidence_score'],
            ),
          ),
        );
      } else {
        _showError('Server Error: ${jsonResponse['message']}');
      }
    } catch (e) {
      setState(() {
        _isLoading = false;
      });
      _showError('Connection failed. Make sure your Colab server is running.');
    }
  }

  void _showError(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: Colors.red),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F7F5),
      appBar: AppBar(
        title: Text('AgroInsight', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, color: const Color(0xFF2E7D32))),
        centerTitle: true,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Welcome, Lead Farmer', style: GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Text('Rutsiro Sector • MVP App Ready', style: GoogleFonts.inter(fontSize: 14, color: Colors.grey[600])),
            const SizedBox(height: 40),
            
            // Status Card
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, 4))],
              ),
              child: Row(
                children: [
                  const Icon(FontAwesomeIcons.circleCheck, color: Color(0xFF2E7D32), size: 30),
                  const SizedBox(width: 16),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Cloud Model Status', style: GoogleFonts.inter(fontSize: 12, color: Colors.grey[500])),
                      Text('Ready for Inference', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
                    ],
                  ),
                ],
              ),
            ),
            
            const Spacer(),
            
            // The Main Scan Button
            Center(
              child: _isLoading 
                ? const CircularProgressIndicator(color: Color(0xFFD84315)) // Shows a spinner while waiting for AI
                : GestureDetector(
                    onTap: _scanLeaf,
                    child: Container(
                      height: 200,
                      width: 200,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: const Color(0xFFD84315),
                        boxShadow: [
                          BoxShadow(color: const Color(0xFFD84315).withOpacity(0.3), blurRadius: 30, spreadRadius: 10, offset: const Offset(0, 10)),
                        ],
                      ),
                      child: const Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(FontAwesomeIcons.camera, color: Colors.white, size: 50),
                          SizedBox(height: 12),
                          Text('SCAN LEAF', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold, letterSpacing: 1.5)),
                        ],
                      ),
                    ),
                  ),
            ),
            const SizedBox(height: 30), // Spacing below the orange button
            
            // Secondary Button: View Heatmap
            Center(
              child: OutlinedButton.icon(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => const FarmHeatmapScreen()),
                  );
                },
                icon: const Icon(FontAwesomeIcons.mapLocationDot, color: Color(0xFF2E7D32)),
                label: Text(
                  'VIEW FARM HEATMAP',
                  style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: const Color(0xFF2E7D32)),
                ),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
                  side: const BorderSide(color: Color(0xFF2E7D32), width: 2),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
                ),
              ),
            ),
            const Spacer(),
          ],
        ),
      ),
    );
  }
}